[package]
name = "ufsreader"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.9.0"
bitstruct = "0.1.1"
static_assertions = "1.1.0"
